import  angular from 'angular';
import  route from 'angular-route';
import  resource from 'angular-resource';
import  bootstrap from 'angular-ui-bootstrap';
import './app.module';
import './app.factory.js';
import './app.route_configs.js';
import './start-page/start_blog.module';
import './edit-article/edit_article.module.js';
import './create-article/create_article.module';
import './start-page/start_blog.component.js';
import './edit-article/edit_article.component.js';
import './create-article/create_article.component.js';
import './edit-article/modal_delete.component.js';
