import  angular from 'angular';
import  route from 'angular-route';
import  resource from 'angular-resource';
import  bootstrap from 'angular-ui-bootstrap';
import  angular_1_router from 'ngcomponentrouter';
import './app.component.js';
import './app.factory.js';
import './app.route_configs.js';
import './start-page/start_blog.component.js';
import './tags/tag.component';
import './blog-forms/form-create/create_article.component.js';
import './blog-forms/form-edit/edit_article.component.js';
import './blog-forms/form-edit/modal_delete.component.js';
// import './start-page/start_blog.module.js';
// import './tags/tag.module';
// import './blog-forms/form-edit/edit_article.module.js';
// import './blog-forms/form-create/create_article.module';
// import './blog-forms/forms.service';
